spring:
  application:
    name: spring-cloud-config-server
  profiles:
    #本地配置
    active: native
    #配置文件存储位置的路径
    cloud:
      config:
        server:
          native:
            search-locations: file=D://work//SpringCloud//SpringCloudConfig
#端口
server:
    port: 8888
